title: Nicolò Rinaldi
author: Nicolò Rinaldi
description: Junior Software Engineer / Data Scientist at Sease
tagline: Junior Software Engineer / Data Scientist at Sease
url: https://nicolo-rinaldi.github.io

# Path to your CV (e.g. cv.pdf in the repo root). Leave empty to hide the RESUME link.
cv:

# Icons: https://fontawesome.com/search?ic=free
social:
  - { name: LinkedIn, icon: fa-brands fa-linkedin, url: "https://www.linkedin.com/in/nicolo-rinaldi/" }
  - { name: GitHub, icon: fa-brands fa-github, url: "https://github.com/nicolo-rinaldi" }
  # - { name: Email, icon: fa-solid fa-envelope, url: "mailto:you@example.com" }

plugins:
  - jekyll-seo-tag

exclude: [README.md]
